// <auto-generated />
using System;
using MemuVie.Evento.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MemuVie.Evento.Models.Evento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorTema")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataEncerramentoVotacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoCapa")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Local")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultadoRevelacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Revelado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoDestaque")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("VotacaoEncerrada")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("MemuVie.Evento.Models.GaleriaPost", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("EventoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlFoto")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlVideo")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("GaleriaPosts");
                });

            modelBuilder.Entity("MemuVie.Evento.Models.TokenRedefinicaoSenha", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("TokensRedefinicaoSenha");
                });

            modelBuilder.Entity("MemuVie.Evento.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoPerfil")
                        .HasMaxLength(1000000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MemuVie.Evento.Models.Voto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConvidadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("EventoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Palpite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConvidadoId");

                    b.HasIndex("EventoId", "ConvidadoId")
                        .IsUnique();

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("MemuVie.Evento.Models.Evento", b =>
                {
                    b.HasOne("MemuVie.Evento.Models.Usuario", "Usuario")
                        .WithMany("Eventos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MemuVie.Evento.Models.GaleriaPost", b =>
                {
                    b.HasOne("MemuVie.Evento.Models.Evento", "Evento")
                        .WithMany("GaleriaPosts")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemuVie.Evento.Models.Usuario", "Usuario")
                        .WithMany("GaleriaPosts")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MemuVie.Evento.Models.TokenRedefinicaoSenha", b =>
                {
                    b.HasOne("MemuVie.Evento.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MemuVie.Evento.Models.Voto", b =>
                {
                    b.HasOne("MemuVie.Evento.Models.Usuario", "Convidado")
                        .WithMany("Votos")
                        .HasForeignKey("ConvidadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemuVie.Evento.Models.Evento", "Evento")
                        .WithMany("Votos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convidado");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("MemuVie.Evento.Models.Evento", b =>
                {
                    b.Navigation("GaleriaPosts");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("MemuVie.Evento.Models.Usuario", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("GaleriaPosts");

                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
